// ts/lib/components/GradeBar.svelte
<!--
Copyright: Ankitects Pty Ltd and contributors
License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
-->
<!--
    pgrep FSRS grade row for the Cards door. Equal monochrome buttons, optional
    next-interval hint under each. Ported from the Claude Design export
    (design/components/study/GradeBar.jsx).
-->
<script lang="ts">
    export let grades: Array<{ label: string; value: number; interval?: string }> = [];
    export let showIntervals = false;
    export let disabled = false;
    export let onGrade: ((value: number) => void) | undefined = undefined;
</script>

<div class="grades" style="grid-template-columns: repeat({grades.length}, 1fr);">
    {#each grades as g (g.value)}
        <button type="button" class="grade" {disabled} on:click={() => onGrade && onGrade(g.value)}>
            <span class="label">{g.label}</span>
            {#if showIntervals && g.interval}
                <span class="interval">{g.interval}</span>
            {/if}
        </button>
    {/each}
</div>

<style lang="scss">
    .grades {
        display: grid;
        gap: 12px;
        font-family: var(--font-ui);
    }

    .grade {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 3px;
        background: none;
        border: var(--hairline);
        border-radius: var(--radius-control);
        padding: 12px 0 10px;
        color: var(--text);
        font-family: inherit;
        cursor: pointer;
        transition: var(--transition-calm);

        &:not([disabled]):hover {
            background: var(--hover-wash);
            border-color: var(--muted);
        }

        &[disabled] {
            cursor: default;
            opacity: 0.55;
        }

        .label {
            font-size: 14px;
            font-weight: 500;
        }

        .interval {
            font-family: var(--font-mono);
            font-size: 11px;
            color: var(--muted);
            font-variant-numeric: tabular-nums;
        }
    }
</style>

// design/claude-design/components/study/GradeBar.jsx
import React from "react";

const DEFAULT_GRADES = [
    { label: "Again", interval: "10m" },
    { label: "Hard", interval: "2d" },
    { label: "Good", interval: "4d" },
    { label: "Easy", interval: "8d" },
];

/** FSRS grade row for the cards door. Four equal monochrome buttons. */
export function GradeBar({ grades = DEFAULT_GRADES, showIntervals = true, onGrade, style }) {
    return (
        <div
            style={{
                display: "grid",
                gridTemplateColumns: `repeat(${grades.length}, 1fr)`,
                gap: 12,
                fontFamily: "var(--font-ui)",
                ...style,
            }}
        >
            {grades.map((g) => (
                <button
                    key={g.label}
                    onClick={() => onGrade && onGrade(g.label)}
                    style={{
                        background: "none",
                        border: "1px solid var(--border)",
                        borderRadius: "var(--radius-control)",
                        padding: "12px 0 10px",
                        color: "var(--text)",
                        cursor: "pointer",
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        gap: 3,
                        fontFamily: "inherit",
                        transition: "background 240ms ease, border-color 240ms ease, color 240ms ease",
                    }}
                >
                    <span style={{ fontSize: 14, fontWeight: 500 }}>{g.label}</span>
                    {showIntervals && (
                        <span
                            style={{
                                fontFamily: "var(--font-mono)",
                                fontSize: 11,
                                color: "var(--muted)",
                                fontVariantNumeric: "tabular-nums",
                            }}
                        >
                            {g.interval}
                        </span>
                    )}
                </button>
            ))}
        </div>
    );
}
