// design/components/study/ChoiceList.jsx
import React from 'react';

/** Five choices A to E. Monochrome default, thin blue outline for select,
    dimmed with a calm blue tag for a committed wrong answer. Never red. */
export function ChoiceList({ choices, onSelect, style }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10, fontFamily: 'var(--font-ui)', ...style }}>
      {choices.map((c) => {
        const selected = c.state === 'selected';
        const committed = c.state === 'committed';
        return (
          <div key={c.key} onClick={() => onSelect && onSelect(c.key)} style={{
            display: 'flex', alignItems: 'center', gap: 16,
            border: selected ? '1.5px solid var(--performance)' : '1px solid var(--border)',
            background: selected ? 'rgba(129,161,193,0.06)' : 'none',
            opacity: committed ? 0.62 : 1,
            borderRadius: 'var(--radius-row)', padding: '14px 18px',
            cursor: onSelect ? 'pointer' : 'default', transition: 'background 240ms ease, border-color 240ms ease, color 240ms ease',
          }}>
            <span style={{
              width: 26, height: 26, flex: '0 0 26px',
              border: `1px solid ${selected ? 'var(--performance)' : 'var(--border)'}`,
              borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontFamily: 'var(--font-mono)', fontSize: 12,
              color: selected ? 'var(--performance-text)' : 'var(--muted)',
            }}>{c.key}</span>
            <span style={{ fontSize: 16, color: 'var(--text)' }}>{c.content}</span>
            {committed && (
              <span style={{ marginLeft: 'auto', fontSize: 11, color: 'var(--performance-text)', border: '1px solid rgba(129,161,193,0.45)', borderRadius: 999, padding: '3px 10px', whiteSpace: 'nowrap' }}>
                Your answer, not correct
              </span>
            )}
          </div>
        );
      })}
    </div>
  );
}

// ts/lib/components/ChoiceList.svelte
<!--
Copyright: Ankitects Pty Ltd and contributors
License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
-->
<!--
    pgrep choice list. Monochrome by default, a thin blue outline for the live
    selection. After commit the row locks: the correct choice takes a calm
    success outline, a wrong commit dims and wears a blue "not correct" tag.
    Never red. Ported from the Claude Design export
    (design/components/study/ChoiceList.jsx), extended with the correct-answer
    reveal the committed backend provides.
-->
<script lang="ts">
    export let choices: Array<{ key: string; html: string }> = [];
    export let selected = "";
    export let committed = false;
    export let correctKey: string | null = null;
    export let onSelect: ((key: string) => void) | undefined = undefined;

    type RowState = "default" | "selected" | "correct" | "wrong" | "locked";

    function rowState(key: string): RowState {
        if (!committed) {
            return key === selected ? "selected" : "default";
        }
        if (correctKey && key === correctKey) {
            return "correct";
        }
        if (key === selected) {
            return "wrong";
        }
        return "locked";
    }
</script>

<div class="choices">
    {#each choices as c (c.key)}
        {@const state = rowState(c.key)}
        <button
            type="button"
            class="choice state-{state}"
            disabled={committed}
            on:click={() => !committed && onSelect && onSelect(c.key)}
        >
            <span class="key">{c.key}</span>
            <span class="content">{@html c.html}</span>
            {#if state === "correct"}
                <span class="tag correct">Correct answer</span>
            {:else if state === "wrong"}
                <span class="tag wrong">Your answer, not correct</span>
            {/if}
        </button>
    {/each}
</div>

<style lang="scss">
    .choices {
        display: flex;
        flex-direction: column;
        gap: 10px;
        font-family: var(--font-ui);
    }

    .choice {
        display: flex;
        align-items: center;
        gap: 16px;
        width: 100%;
        text-align: left;
        border: var(--hairline);
        background: none;
        border-radius: var(--radius-row);
        padding: 14px 18px;
        color: var(--text);
        cursor: pointer;
        transition: var(--transition-calm);

        &:not([disabled]):hover {
            border-color: var(--muted);
        }

        &[disabled] {
            cursor: default;
        }
    }

    .state-selected {
        border-color: var(--performance);
        border-width: 1.5px;
        background: rgba(129, 161, 193, 0.06);
    }

    .state-correct {
        border-color: var(--success);
        border-width: 1.5px;
        background: rgba(163, 190, 140, 0.08);
    }

    .state-wrong {
        opacity: 0.62;
    }

    .state-locked {
        opacity: 0.5;
    }

    .key {
        flex: 0 0 26px;
        width: 26px;
        height: 26px;
        display: flex;
        align-items: center;
        justify-content: center;
        border: var(--hairline);
        border-radius: 8px;
        font-family: var(--font-mono);
        font-size: 12px;
        color: var(--muted);
    }

    .state-selected .key {
        border-color: var(--performance);
        color: var(--performance-text);
    }

    .state-correct .key {
        border-color: var(--success);
        color: var(--text);
    }

    .content {
        font-size: 16px;
        line-height: 1.5;
        color: var(--text);

        :global(p) {
            margin: 0;
        }
    }

    .tag {
        margin-left: auto;
        flex: 0 0 auto;
        font-size: 11px;
        border-radius: var(--radius-pill);
        padding: 3px 10px;
        white-space: nowrap;

        &.correct {
            color: var(--text);
            border: 1px solid var(--success);
        }

        &.wrong {
            color: var(--performance-text);
            border: 1px solid rgba(129, 161, 193, 0.45);
        }
    }
</style>
